worker_processes auto;
events { worker_connections 1024; }

http {
    # Zdefiniowany blok upstream wskazujący na serwis aplikacji
    # 'app' to nazwa serwisu z docker-compose.yml, a 8000 to port wewnątrz kontenera
    upstream backend_app {
        server app:8000;
    }

    server {
        listen 80;
        server_name _;

        # Przekazywanie wszystkich żądań do zdefiniowanego wyżej upstreamu
        location / {
            proxy_pass http://backend_app/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            # Dobrą praktyką jest również dodanie tych dwóch nagłówków:
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}